[package]
name = "slot-algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
plotters = "0.3"
once_cell = "1.20"
validator = { version = "0.18", features = ["derive"] }